Repository ha3158987/SolarConnect, pull requests merged in 2021-08, with the labels that each got.

#5 [feat / setup] reset.css 설정 및 글로벌 스타일 적용
  src/App.js
  src/common/SortedOutputBox.jsx
  src/common/UTCTimer.jsx
  src/components/body/UserInput.jsx
  src/components/header/Header.jsx
  src/style/reset.js
Labels: feature, set up

#8 feat/timer #7
  package-lock.json
  src/common/SortedOutputBox.jsx
  src/common/UTCTimer.jsx
  src/components/body/UserInput.jsx
  src/components/header/Header.jsx
  src/style/reset.js
  yarn.lock
Labels: feature

#11 [merge / refactor] 브랜치 병합 및 전반적인 리팩토링
  src/App.jsx
  src/common/SortedOutputBox.jsx
  src/common/Timer.jsx
  src/common/UTCTimer.jsx
  src/components/body/SortedOutputs.jsx
  src/components/body/UserInput.jsx
  src/components/header/Header.jsx
  src/components/pages/MainPage.jsx
  src/icons/logo.svg
  src/index.js
  src/utils/context/context.js
  src/utils/context/sortReducer.js
Labels: refactoring

#12 feat: 숫자 정렬로직 구현 (#6)
  src/common/SortedOutputBox.jsx
  src/components/body/SortedOutputs.jsx
  src/components/body/UserInput.jsx
  src/components/pages/MainPage.jsx
  src/utils/context/sortReducer.js
Labels: refactoring, feature

#16 Readme.md 본문 업데이트 (#14)
  README.md
Labels: doc

#21 [fix] 3초 뒤 내림차순 정렬 렌더링 로직 구현 (#20)
  README.md
  src/common/SortedOutputBox.jsx
  src/components/body/SortedOutputs.jsx
  src/components/body/UserInput.jsx
  src/components/pages/MainPage.jsx
  src/utils/hooks/useSort.js
Labels: bug, refactoring, feature
